export const MessageType = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  CHAT_JOIN: 'CHAT_JOIN',
  CHAT_LEAVE: 'CHAT_LEAVE',
  PLAYER_INPUT: 'PLAYER_INPUT',
  PLAYER_JOIN: 'PLAYER_JOIN',
  PLAYER_LEAVE: 'PLAYER_LEAVE',
  INIT_GAME_STATE: 'INIT_GAME_STATE',
  UPDATE_GAME_STATE: 'UPDATE_GAME_STATE',
};

export const {
  CHAT_MESSAGE,
  CHAT_JOIN,
  CHAT_LEAVE,
  PLAYER_INPUT,
  PLAYER_JOIN,
  PLAYER_LEAVE,
  INIT_GAME_STATE,
  UPDATE_GAME_STATE,
} = MessageType;