/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { modelUrls } from '../utils/models';

export default function Boat(props) {
  const { nodes, materials } = useGLTF(modelUrls.boat);
  return (
    <group {...props} dispose={null}>
      <group name="Scene" position={[0, 1.4, 0]}>
        <mesh
          name="Лодка"
          castShadow
          receiveShadow
          geometry={nodes.Лодка.geometry}
          material={materials['Светлое дерево']}
          position={[0, -0.719, 8.951]}
        />
        <mesh
          name="Рамка_лодки"
          castShadow
          receiveShadow
          geometry={nodes.Рамка_лодки.geometry}
          material={materials['Темное дерево']}
          position={[-5.356, -0.246, 9.261]}
          rotation={[0, 0, -0.235]}
          scale={0.204}
        />
        <mesh
          name="Шпангоуты"
          castShadow
          receiveShadow
          geometry={nodes.Шпангоуты.geometry}
          material={materials['Темное дерево']}
          position={[2.624, -0.719, 9.022]}
          scale={[1, 1, 0.699]}
        />
        <group name="Плавник" position={[5.103, -1.072, 9.259]} scale={[0.311, 1, 0.033]}>
          <mesh
            name="Cube015"
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials['Светлое дерево']}
          />
          <mesh
            name="Cube015_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials['Темное дерево']}
          />
        </group>
        <mesh
          name="Сиденья"
          castShadow
          receiveShadow
          geometry={nodes.Сиденья.geometry}
          material={materials['Темное дерево']}
          position={[2.642, -0.693, 9.26]}
          scale={[0.338, 0.074, 1]}
        />
        <mesh
          name="Мачта"
          castShadow
          receiveShadow
          geometry={nodes.Мачта.geometry}
          material={materials['Темное дерево']}
          position={[0.224, -0.055, 9.092]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[-0.058, -1.819, -0.058]}
        />
        <mesh
          name="Большой_парус"
          castShadow
          receiveShadow
          geometry={nodes.Большой_парус.geometry}
          material={materials.Парус}
          position={[1.608, 2.991, 4.969]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={5.956}
        />
        <mesh
          name="Малый_парус"
          castShadow
          receiveShadow
          geometry={nodes.Малый_парус.geometry}
          material={materials.Парус}
          position={[-5.032, 1.214, 5.379]}
          rotation={[1.549, 0.311, -0.003]}
          scale={5.013}
        />
      </group>
    </group>
  )
}
