/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { modelUrls } from '../utils/models';

export default function FishHouse(props) {
  const { nodes, materials } = useGLTF(modelUrls.fish_house);
  return (
     <group {...props} dispose={null}>
      <group name="Scene" position={[0, -0.7, 0]}>
         <mesh
           name="Мостки"
           castShadow
           receiveShadow
           geometry={nodes.Мостки.geometry}
           material={materials['Рамка крыши']}
           scale={[5.093, 3.793, 3.793]}
         />
         <mesh
           name="Бревна"
           castShadow
           receiveShadow
           geometry={nodes.Бревна.geometry}
           material={materials.Дерево}
           position={[0, 0, -3.84]}
           rotation={[-Math.PI, 0, -Math.PI]}
           scale={[-0.163, -1.526, -0.163]}
         />
         <group
           name="Дом"
           position={[0, 2.274, 0]}
           rotation={[-Math.PI, 0, 0]}
           scale={[-3.124, -1, -2.19]}>
           <mesh
             name="Cube001"
             castShadow
             receiveShadow
             geometry={nodes.Cube001.geometry}
             material={materials.Дерево}
           />
           <mesh
             name="Cube001_1"
             castShadow
             receiveShadow
             geometry={nodes.Cube001_1.geometry}
             material={materials['Рама окон']}
           />
           <mesh
             name="Cube001_2"
             castShadow
             receiveShadow
             geometry={nodes.Cube001_2.geometry}
             material={materials.Дверь}
           />
           <mesh
             name="Cube001_3"
             castShadow
             receiveShadow
             geometry={nodes.Cube001_3.geometry}
             material={materials.Окно}
           />
         </group>
         <mesh
           name="Крыша"
           castShadow
           receiveShadow
           geometry={nodes.Крыша.geometry}
           material={materials.Крыша}
           position={[-0.327, 2.274, -0.722]}
           rotation={[-2.269, 0, 0]}
           scale={[-3.124, -1, -2.19]}
         />
         <mesh
           name="Малая_крыша"
           castShadow
           receiveShadow
           geometry={nodes.Малая_крыша.geometry}
           material={materials.Крыша}
           position={[-5.11, 0.768, -0.704]}
           rotation={[-2.269, 0, 0]}
           scale={[-3.124, -1, -2.19]}
         />
         <mesh
           name="Ручка"
           castShadow
           receiveShadow
           geometry={nodes.Ручка.geometry}
           material={materials.Ручка}
           position={[-1.128, -0.589, 3.494]}
           rotation={[0, 0, Math.PI / 2]}
           scale={0.735}
         />
         <mesh
           name="Рамка_крыши"
           castShadow
           receiveShadow
           geometry={nodes.Рамка_крыши.geometry}
           material={materials['Рамка крыши']}
           position={[-0.016, 6.505, -0.373]}
           rotation={[Math.PI / 4, 0, 0]}
           scale={[1.838, 0.091, 0.094]}
         />
         <mesh
           name="Рамка_малой_крыши"
           castShadow
           receiveShadow
           geometry={nodes.Рамка_малой_крыши.geometry}
           material={materials['Рамка крыши']}
           position={[-3.027, 4.65, -0.373]}
           rotation={[Math.PI / 4, 0, 0]}
           scale={[0.836, 0.042, 0.043]}
         />
       </group>
     </group>
   )
}
