/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { modelUrls } from '../utils/models';

export default function Island(props) {
  const { scene } = useGLTF(modelUrls.island);
  return (
     <primitive
       object={scene}
       scale={5}
      position={[100, 5, 100]} // Позиция модели
     />
   );
}
